language: python
python:
- '2.7'
install:
- bundle install
- pip install -r requirements.txt
script: python app_tests.py
deploy:
  provider: heroku
  api_key:
    secure: Z4oiFHZoamHwTxb4QFK8jAnCF/QtkUUY8dATtfTyN/DwBHKW2FtAfNhFjboL7WngkV+PQfdzoHfmFqTjoYQZeOaFT7lkvnSfVFby2/4EMkv8eZoyop86ad/QMJ8pRAVG+nEUSu0gFBKUMb/iuvVbDDQSGtuaiwoojyOPv/owAF4=
  app: lr-concept-my-property
  on:
    repo: LandRegistry/concept-my-property
  strategy: git
